"""Canonical website, search, and playable-site dictionaries.

Both local_intents.py and brain/action_planner.py need these tables.
Keeping them here avoids a circular import (local_intents → tools → router
→ action_planner → local_intents).
"""

from __future__ import annotations

WEBSITE_ALIASES = {
    "amazon": "https://www.amazon.com/",
    "ap classroom": "https://myap.collegeboard.org/",
    "apple": "https://www.apple.com/",
    "bing": "https://www.bing.com/",
    "canva": "https://www.canva.com/",
    "chat gpt": "https://chatgpt.com/",
    "chatgpt": "https://chatgpt.com/",
    "claude": "https://claude.ai/",
    "cnn": "https://www.cnn.com/",
    "college board": "https://www.collegeboard.org/",
    "discord": "https://discord.com/app",
    "docs": "https://docs.google.com/",
    "drive": "https://drive.google.com/",
    "dropbox": "https://www.dropbox.com/",
    "duck duck go": "https://duckduckgo.com/",
    "duckduckgo": "https://duckduckgo.com/",
    "ebay": "https://www.ebay.com/",
    "espn": "https://www.espn.com/",
    "facebook": "https://www.facebook.com/",
    "fb": "https://www.facebook.com/",
    "figma": "https://www.figma.com/",
    "gamma": "https://gamma.app/",
    "gemini": "https://gemini.google.com/app",
    "github": "https://github.com/",
    "gmail": "https://mail.google.com/",
    "google": "https://www.google.com/",
    "google classroom": "https://classroom.google.com/",
    "google docs": "https://docs.google.com/",
    "google drive": "https://drive.google.com/",
    "google maps": "https://www.google.com/maps",
    "google sheets": "https://sheets.google.com/",
    "google slides": "https://slides.google.com/",
    "hulu": "https://www.hulu.com/",
    "ig": "https://www.instagram.com/",
    "insta": "https://www.instagram.com/",
    "instagram": "https://www.instagram.com/",
    "git hub": "https://github.com/",
    "khan academy": "https://www.khanacademy.org/",
    "linkedin": "https://www.linkedin.com/",
    "maps": "https://www.google.com/maps",
    "max": "https://www.max.com/",
    "medium": "https://medium.com/",
    "netflix": "https://www.netflix.com/",
    "new york times": "https://www.nytimes.com/",
    "notion": "https://www.notion.so/",
    "nyt": "https://www.nytimes.com/",
    "openai": "https://openai.com/",
    "pinterest": "https://www.pinterest.com/",
    "prime video": "https://www.primevideo.com/",
    "reddit": "https://www.reddit.com/",
    "sheets": "https://sheets.google.com/",
    "slides": "https://slides.google.com/",
    "snap": "https://www.snapchat.com/",
    "snapchat": "https://www.snapchat.com/",
    "soundcloud": "https://soundcloud.com/",
    "spotfy": "https://open.spotify.com/",
    "stackoverflow": "https://stackoverflow.com/",
    "stack overflow": "https://stackoverflow.com/",
    "spotifiy": "https://open.spotify.com/",
    "spotufy": "https://open.spotify.com/",
    "spotify": "https://open.spotify.com/",
    "target": "https://www.target.com/",
    "threads": "https://www.threads.net/",
    "tiktok": "https://www.tiktok.com/",
    "tik tok": "https://www.tiktok.com/",
    "twitch": "https://www.twitch.tv/",
    "twitter": "https://x.com/",
    "walmart": "https://www.walmart.com/",
    "weather": "https://weather.com/",
    "wikipedia": "https://www.wikipedia.org/",
    "x": "https://x.com/",
    "yahoo": "https://www.yahoo.com/",
    "youtube": "https://www.youtube.com/",
    "you tube": "https://www.youtube.com/",
    "yt": "https://www.youtube.com/",
    "zoom": "https://zoom.us/",
}

SITE_SEARCH_ALIASES = {
    "git hub": "github",
    "you tube": "youtube",
    "tik tok": "tiktok",
    "chat gpt": "chatgpt",
    "duck duck go": "duckduckgo",
    "stack overflow": "stackoverflow",
    "spotfy": "spotify",
    "spotifiy": "spotify",
    "spotufy": "spotify",
    "sound cloud": "soundcloud",
}

PLAYABLE_SITE_ALIASES = {
    "spotify": "spotify",
    "spotufy": "spotify",
    "spotfy": "spotify",
    "spotifiy": "spotify",
    "youtube": "youtube",
    "you tube": "youtube",
    "yt": "youtube",
    "soundcloud": "soundcloud",
    "sound cloud": "soundcloud",
    "tiktok": "tiktok",
    "tik tok": "tiktok",
    "twitch": "twitch",
}
